### PR TITLE
Update to PhotonLib v2023.4.1

### PR DESCRIPTION
**Pull request by auscompgeek**
Patches:

- https://github.com/PhotonVision/photonvision/pull/843
- https://github.com/PhotonVision/photonvision/pull/844

### CODE REVIEW

**Comment by virtuald** [comment]
I added OpenCV but your patch is broken now.

Can we just open an issue with upstream and have them not make the camera mandatory? I'm not sure we want to carry a patch for this long term.

**Comment by auscompgeek** [comment]
> Can we just open an issue with upstream and have them not make the camera mandatory? I'm not sure we want to carry a patch for this long term.

The PR is already open: https://github.com/PhotonVision/photonvision/pull/797

**Comment by auscompgeek** [comment]
Ugh, looking at that new code that is rather annoying. Maybe the way to go is to revert that PnP stuff.

**Comment by auscompgeek** [comment]
> Maybe the way to go is to revert that PnP stuff.

The PnP commit doesn't revert cleanly unfortunately.

I tried throwing in a ctor taking unique_ptr, but now it's unhappy with the `cv::Mat` usages :upside_down_face:

**Pull request merged**
